config/routes.rb
Rails.application.routes.draw do
  resources :pet_histories
  resources :pets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
    has_many :pet_histories
end

app/models/pet_history.rb
class PetHistory < ApplicationRecord
    belongs_to :pet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pet_histories_controller.rb
class PetHistoriesController < ApplicationController
  before_action :set_pet_history, only: %i[ show edit update destroy ]

  # GET /pet_histories or /pet_histories.json
  def index
    @pet_histories = PetHistory.all
  end

  # GET /pet_histories/1 or /pet_histories/1.json
  def show
  end

  # GET /pet_histories/new
  def new
    @pet_history = PetHistory.new
    Pets = Pet.all
  end

  # GET /pet_histories/1/edit
  def edit
    @pets = pet.all
  end

  # POST /pet_histories or /pet_histories.json
  def create
    @pet_history = PetHistory.new(pet_history_params)

    respond_to do |format|
      if @pet_history.save
        format.html { redirect_to pet_history_url(@pet_history), notice: "Pet history was successfully created." }
        format.json { render :show, status: :created, location: @pet_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_histories/1 or /pet_histories/1.json
  def update
    respond_to do |format|
      if @pet_history.update(pet_history_params)
        format.html { redirect_to pet_history_url(@pet_history), notice: "Pet history was successfully updated." }
        format.json { render :show, status: :ok, location: @pet_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_histories/1 or /pet_histories/1.json
  def destroy
    @pet_history.destroy

    respond_to do |format|
      format.html { redirect_to pet_histories_url, notice: "Pet history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_history
      @pet_history = PetHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_history_params
      params.require(:pet_history).permit(:weight, :height, :description)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :birthdate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pet_histories_helper.rb
module PetHistoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VeterinarioApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pet_histories/_form.html.erb
<%= form_with(model: pet_history) do |form| %>
  <% if pet_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet_history.errors.count, "error") %> prohibited this pet_history from being saved:</h2>

      <ul>
        <% pet_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


<div>
     <%= form.label%>
     <%  form.select :pet_id , option_from_collection_for_select(@pets, :id, :name) %>         
</div>

app/views/pet_histories/_pet_history.html.erb
<div id="<%= dom_id pet_history %>">
  <p>
    <strong>Weight:</strong>
    <%= pet_history.weight %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= pet_history.height %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= pet_history.description %>
  </p>

  def pet_history_params
       params.require(:pet_history.permit(weight, :height, :description, :pet_id))
  end  

</div>

app/views/pet_histories/edit.html.erb
<h1>Editing pet history</h1>

<%= render "form", pet_history: @pet_history %>

<br>

<div>
  <%= link_to "Show this pet history", @pet_history %> |
  <%= link_to "Back to pet histories", pet_histories_path %>
</div>

app/views/pet_histories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pet histories</h1>

<div id="pet_histories">
  <% @pet_histories.each do |pet_history| %>
    <%= render pet_history %>
    <p>
      <%= link_to "Show this pet history", pet_history %>
    </p>
  <% end %>
</div>

<%= link_to "New pet history", new_pet_history_path %>

app/views/pet_histories/new.html.erb
<h1>New pet history</h1>

<%= render "form", pet_history: @pet_history %>

<br>

<div>
  <%= link_to "Back to pet histories", pet_histories_path %>
</div>

app/views/pet_histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pet_history %>

<div>
  <%= link_to "Edit this pet history", edit_pet_history_path(@pet_history) %> |
  <%= link_to "Back to pet histories", pet_histories_path %>

  <%= button_to "Destroy this pet history", @pet_history, method: :delete %>
</div>

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.date_field :name %>
  </div>

  <div>
    <%= form.label :birthdate, style: "display: block" %>
    <%= form.date_field :birthdate %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<div id="<%= dom_id pet %>">
  <p>
    <strong>Name:</strong>
    <%= pet.name %>
  </p>

  <p>
    <strong>Birthdate:</strong>
    <%= pet.birthdate %>
  </p>

</div>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Show this pet", @pet %> |
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pets</h1>

<div id="pets">
  <% @pets.each do |pet| %>
    <%= render pet %>
    <p>
      <%= link_to "Show this pet", pet %>
    </p>
  <% end %>
</div>

<%= link_to "New pet", new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pet %>

<div>
  <%= link_to "Edit this pet", edit_pet_path(@pet) %> |
  <%= link_to "Back to pets", pets_path %>

  <%= button_to "Destroy this pet", @pet, method: :delete %>
</div>